const citiesInMorocco = [
    'Agadir',
    'Ahfir',
    'Ain El Aouda',
    'Ain Harrouda',
    'Al Hoceima',
    'Amizmiz',
    'Asilah',
    'Aourir',
    'Azemmour',
    'Azrou',
    'Beni Ansar',
    'Beni Mellal',
    'Ben Guerir',
    'Ben Slimane',
    'Bejaad',
    'Berkane',
    'Berrechid',
    'Bir Gandouz',
    'Bir Jdid',
    'Bouarfa',
    'Boujdour',
    'Boulemane',
    'Bouznika',
    'Casablanca',
    'Chefchaouen',
    'Chichaoua',
    'Dakhla',
    'Demnate',
    'Drargua',
    'El Hajeb',
    'El Jadida',
    'El Kelaa des Sraghna',
    'El Youssoufia',
    'Errachidia',
    'Essaouira',
    'Fes',
    'Fes el Bali',
    'Fkih Ben Salah',
    'Fnideq',
    'Gueliz',
    'Guelmim',
    'Guercif',
    'Had Soualem',
    'Ifrane',
    'Imlil',
    'Imzouren',
    'Jorf El Melha',
    'Kenitra',
    'Khemisset',
    'Ksar el-Kebir',
    'Khémis Zmamra',
    'Khouribga',
    'Ksar el-Kebir',
    'Laayoune',
    'Larache',
    'Lqliaa',
    'Marrakesh',
    'Martil',
    'M’diq',
    'Meknes',
    'Midelt',
    'Mohammedia',
    'Moulay Bousselham',
    'Nador',
    'Ouarzazate',
    'Oued Zem',
    'Oujda',
    'Ouazzane',
    'Oulad Ayad',
    'Oulad Berhil',
    'Oulad Teima',
    'Rabat',
    'Rissani',
    'Safi',
    'Salé',
    'Sebt Gzoula',
    'Sefrou',
    'Settat',
    'Sidi Azzouz',
    'Sidi Bennour',
    'Sidi Ifni',
    'Sidi Kacem',
    'Sidi Slimane',
    'Sidi Taibi',
    'Sidi Yahya El Gharb',
    'Skhirat',
    'Tafraout',
    'Tamesna',
    'Tangier',
    'Tantan',
    'Taroudant',
    'Tarfaya',
    'Taza',
    'Taznakht',
    'Tetuán',
    'Tinghir',
    'Tiznit',
    'Youssoufia',
    'Zagora'
];

export default citiesInMorocco